"""EMOSA GRE termination point (GTP): the gateway end of every pod's OpenSync GRE.

An OpenSync 6.6 pod joins its uplink as a 3-address station, leases a
link-local address, and builds a gretap to the first host of that subnet
(``cm2_bh_gre.c``). The GTP is that first host. It:

- owns ``.1`` of a link-local underlay subnet on the underlay interface (the
  segment where the gateway's pod-backhaul SSID lands);
- serves DHCP there with dnsmasq: interface MTU (option 26), no router, no
  DNS. Every lease event runs ``emosa-gtp lease``;
- keeps one gretap per leased pod, bridged into the gateway LAN bridge, and
  removes it when the lease ends or the pod's address changes.

It never bridges the underlay itself into the LAN. The design is in
doc/architecture/data-plane.md §4; the contract is spec §8.

    emosa-gtp setup CONFIG            addresses, bridge, dnsmasq configuration, reconcile
    emosa-gtp lease CONFIG ACTION MAC IP [HOST]    (dnsmasq --dhcp-script: add, old, del)
    emosa-gtp reconcile CONFIG        tunnels = current leases
    emosa-gtp list CONFIG
"""

import argparse
import ipaddress
import json
import logging
import os
import re
import subprocess
import sys
import time
from pathlib import Path

from emosa.config import validate

log = logging.getLogger("emosa.gtp")

GRETAP_OVERHEAD = 38  # outer IPv4 20 + GRE 4 + inner Ethernet 14
LINK_LOCAL = ipaddress.ip_network("169.254.0.0/16")
MAC = re.compile(r"[0-9a-f]{2}(:[0-9a-f]{2}){5}")


class ConfigError(ValueError):
    pass


def load(path):
    config = json.loads(Path(path).read_text())
    validate("gtp-config", config)
    check(config)
    return config


def check(config):
    """The rules JSON Schema cannot state: OpenSync's link-local and .1 requirements."""
    underlay = config["underlay"]
    address = ipaddress.ip_interface(underlay["address"])
    network = address.network
    if not network.subnet_of(LINK_LOCAL):
        raise ConfigError(
            "the underlay must be link-local (169.254.0.0/16): OpenSync builds no GRE otherwise"
        )
    if int(address.ip) != int(network.network_address) + 1:
        raise ConfigError(
            "the GTP must be the first host (.1) of the underlay subnet: OpenSync's GRE remote"
        )
    first, last = (ipaddress.ip_address(a) for a in underlay["dhcp_range"])
    if not (first in network and last in network and address.ip < first <= last):
        raise ConfigError("the DHCP range must lie in the underlay subnet, above .1")
    if config["tunnel_mtu"] + GRETAP_OVERHEAD > underlay["mtu"]:
        raise ConfigError("underlay MTU too small for the tunnel MTU plus 38 bytes of gretap")
    return config


def tunnel_name(ip):
    """gtp<third>_<fourth> octet, as mv3's pgd<b3>_<b4>: at most 15 characters."""
    b = ipaddress.ip_address(ip).packed
    return f"gtp{b[2]}_{b[3]}"


class Links:
    """The host's links, through iproute2. Tests replace ``run``."""

    def __init__(self, run=None):
        self.run = run or self._run

    @staticmethod
    def _run(*args, check=True):
        return subprocess.run(["ip", *args], capture_output=True, text=True, check=check).stdout

    def exists(self, name):
        return bool(self.run("-br", "link", "show", "dev", name, check=False).strip())

    def ports(self, bridge):
        out = self.run("-o", "link", "show", "master", bridge, check=False)
        return [m.group(1) for m in re.finditer(r"^\d+: ([^:@\s]+)", out, re.M)]

    def gretaps(self):
        """Our tunnels: name -> (local, remote, pinned underlay device or None)."""
        out = self.run("-d", "-o", "link", "show", "type", "gretap", check=False)
        tunnels = {}
        for line in out.splitlines():
            m = re.match(r"\d+: (gtp\d+_\d+)[@:].* remote (\S+) local (\S+)(?: dev (\S+))?", line)
            if m:
                tunnels[m.group(1)] = (m.group(3), m.group(2), m.group(4))
        return tunnels


def render_dnsmasq(config, config_path):
    u = config["underlay"]
    network = ipaddress.ip_interface(u["address"]).network
    first, last = u["dhcp_range"]
    state = Path(config["state_dir"])
    return "\n".join(
        [
            "# generated by emosa-gtp setup; do not edit",
            f"interface={u['interface']}",
            "bind-dynamic",
            "except-interface=lo",
            "port=0",  # no DNS service on the underlay
            f"dhcp-range={first},{last},{network.netmask},{u['lease_time']}",
            f"dhcp-option=option:mtu,{u['mtu']}",
            "dhcp-option=option:router",  # none: the pod's default route stays on br-home
            "dhcp-option=option:dns-server",  # none
            f"dhcp-leasefile={state / 'leases'}",
            f"dhcp-script={state / 'hook'}",
            "script-on-renewal",
            "user=root",  # the hook changes links
            f"pid-file={state / 'dnsmasq.pid'}",
            "",
        ]
    ), (f'#!/bin/sh\nexec {sys.executable} -m emosa.gtp lease "{config_path}" "$@"\n')


class GTP:
    def __init__(self, config, links=None):
        self.config, self.links = config, links or Links()
        self.underlay = config["underlay"]["interface"]
        self.local = str(ipaddress.ip_interface(config["underlay"]["address"]).ip)
        self.bridge = config["lan"]["bridge"]

    def setup(self, config_path):
        u, lan = self.config["underlay"], self.config["lan"]
        run = self.links.run
        if not self.links.exists(self.underlay):
            raise ConfigError(f"underlay interface {self.underlay} does not exist")
        # A bridge carries only what its smallest port does: raise the ports too
        # (the pod-backhaul AP interface), as mv3 runs its backhaul AP at 1600.
        for port in self.links.ports(self.underlay):
            run("link", "set", port, "mtu", str(u["mtu"]))
        run("link", "set", self.underlay, "mtu", str(u["mtu"]), "up")
        run("addr", "replace", u["address"], "dev", self.underlay)
        if not self.links.exists(self.bridge):
            run("link", "add", self.bridge, "type", "bridge")
        run("link", "set", self.bridge, "up")
        for port in lan["ports"]:
            if not self.links.exists(port):
                raise ConfigError(f"LAN port {port} does not exist")
            run("link", "set", port, "master", self.bridge, "up")
        state = Path(self.config["state_dir"])
        state.mkdir(mode=0o755, parents=True, exist_ok=True)
        conf, hook = render_dnsmasq(self.config, Path(config_path).resolve())
        (state / "dnsmasq.conf").write_text(conf)
        (state / "hook").write_text(hook)
        os.chmod(state / "hook", 0o755)
        return self.reconcile()

    def leases(self):
        """Current leases from dnsmasq's lease file: ip -> mac."""
        path = Path(self.config["state_dir"]) / "leases"
        leases = {}
        if path.exists():
            now = time.time()
            for line in path.read_text().splitlines():
                parts = line.split()
                if len(parts) >= 3 and (parts[0] == "0" or int(parts[0]) > now):
                    leases[parts[2]] = parts[1].lower()
        return leases

    def ensure(self, ip):
        name = tunnel_name(ip)
        current = self.links.gretaps().get(name)
        # Tunnels are routed by address, not pinned to the underlay device: an AP that
        # recreates its bridge (hostapd does on restart) must not leave a dead tunnel.
        if current == (self.local, ip, None):
            return name
        if current is not None:
            self.links.run("link", "del", name)
        run = self.links.run
        run("link", "add", name, "type", "gretap", "local", self.local, "remote", ip)
        run("link", "set", name, "mtu", str(self.config["tunnel_mtu"]))
        run("link", "set", name, "master", self.bridge, "up")
        log.info("tunnel %s: %s -> %s in %s", name, self.local, ip, self.bridge)
        return name

    def remove(self, ip):
        name = tunnel_name(ip)
        if name in self.links.gretaps():
            self.links.run("link", "del", name)
            log.info("tunnel %s removed (%s)", name, ip)

    def lease(self, action, mac, ip):
        """One dnsmasq lease event."""
        address = ipaddress.ip_address(ip)
        network = ipaddress.ip_interface(self.config["underlay"]["address"]).network
        if address not in network or not MAC.fullmatch(mac.lower()):
            raise ConfigError("lease outside the underlay")
        if action in ("add", "old"):
            self.ensure(ip)
        elif action == "del":
            self.remove(ip)
        return self.list()

    def reconcile(self):
        wanted = set(self.leases())
        for name, (_, remote, _) in self.links.gretaps().items():
            if remote not in wanted:
                self.links.run("link", "del", name)
        for ip in sorted(wanted):
            self.ensure(ip)
        return self.list()

    def list(self):
        leases = self.leases()
        return {
            name: {"remote": remote, "mac": leases.get(remote)}
            for name, (_, remote, _) in sorted(self.links.gretaps().items())
        }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=("setup", "lease", "reconcile", "list"))
    parser.add_argument("config", type=Path)
    parser.add_argument("event", nargs="*", help="lease: ACTION MAC IP [HOSTNAME]")
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s"
    )
    gtp = GTP(load(args.config))
    if args.command == "setup":
        result = gtp.setup(args.config)
    elif args.command == "lease":
        if len(args.event) < 3:
            parser.error("lease needs ACTION MAC IP")
        action, mac, ip = args.event[:3]
        if action not in ("add", "old", "del"):
            return  # dnsmasq also reports tftp and init events
        result = gtp.lease(action, mac, ip)
    elif args.command == "reconcile":
        result = gtp.reconcile()
    else:
        result = gtp.list()
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
